# docker-compose.yml
version: "3.9"
services:
  postgres:
    container_name: $DB_USER
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
      PG_DATA: /var/lib/postgresql/data
    ports:
      - $DB_PORT:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - pgdata:/var/lib/postgresql/data
    restart: always
  main:
    container_name: main
    build:
      context: .
      dockerfile: ./Dockerfile
    image: task_auto_sharing_main:latest
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - $APP_PORT:3000
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always

volumes:
  pgdata: